"""Comprehensive data verification — audit report.

Reads raw data, applies all rules, and runs a battery of consistency checks
to surface any errors or inconsistencies. Writes a detailed report to
`audit_report.md` and prints to stdout.

Checks performed:
    1. Load consistency (row counts, no duplicate serials)
    2. Per region — class/status counts sum to n_total
    3. N/P rows match the raw value 'N' / 'P'
    4. Asymmetric rows: regex match, right/left split correct
    5. Cleaned codes match the rule: full→same, partial→N/P stripped
    6. partial_ambiguous justification:
        - 'partial' class → automatic (had N/P inside, missing info)
        - 'full' class → must be substring of another code in the region
    7. n_unique recomputed from scratch matches the summary
    8. Shannon entropy recomputed matches the summary
    9. H ≤ log2(n_unique) (information-theoretic upper bound)
   10. Rank-frequency percent sum ≈ 100% per (region, version)
   11. Top code detection — flags ties (multiple codes with the max count)
   12. Color/pattern decomposition — each full/partial wolf has both
   13. Cross-region — every wolf has all 9 region statuses
"""

from __future__ import annotations

import sys
from io import StringIO

import numpy as np
import pandas as pd

from wolf_lib import (
    OUTPUT_DIR,
    REGIONS,
    clean_partial,
    codes_for_version,
    load_data,
    process_all_regions,
    rank_frequency,
    region_summary,
    shannon_entropy_bits,
    split_asymmetric,
)


# ---------------------------------------------------------------------------
# Output buffering — we tee to both stdout and a markdown report
# ---------------------------------------------------------------------------

class Tee:
    def __init__(self):
        self.streams = [sys.stdout, StringIO()]

    def write(self, s):
        for st in self.streams:
            st.write(s)

    def flush(self):
        for st in self.streams:
            st.flush()

    def get_report(self) -> str:
        return self.streams[1].getvalue()


tee = Tee()


def out(s: str = "") -> None:
    tee.write(s + "\n")


def section(title: str, char: str = "=") -> None:
    out()
    out(char * 78)
    out(title)
    out(char * 78)


def check(label: str, ok: bool, detail: str = "", issues_list=None) -> bool:
    mark = "OK " if ok else "!! "
    out(f"  [{mark}] {label}" + (f"  ({detail})" if detail else ""))
    if not ok and issues_list is not None:
        issues_list.append(f"{label}{(' — ' + detail) if detail else ''}")
    return ok


# ---------------------------------------------------------------------------
# Main audit
# ---------------------------------------------------------------------------

def main() -> None:
    issues = []

    raw_full = load_data(only_with_pictures=False)
    df = load_data(only_with_pictures=True)
    proc = process_all_regions(df)

    section("AUDIT REPORT — Wolf Pelt Pattern Analysis")
    out("Wolf pelt data: 9 regions, classification rules per the methodology document")
    out(f"Generated by: step1c_audit.py")

    # ----- 1. Load -----
    section("[1] DATA LOAD")
    out(f"  Total rows in source sheet      : {len(raw_full)}")
    out(f"  Rows with #pictures > 0         : {len(df)}")
    out(f"  Excluded (no pictures)          : {len(raw_full) - len(df)}")

    sns = df["serial number"].astype(str)
    dup = sns[sns.duplicated()].tolist()
    check("Serial numbers all unique", not dup,
          f"duplicates: {dup}" if dup else "", issues)

    # Picture stats
    pics = pd.to_numeric(df["#pictures"], errors="coerce")
    out(f"  Pictures per wolf — min={int(pics.min())}, median={int(pics.median())}, "
        f"mean={pics.mean():.1f}, max={int(pics.max())}, sum={int(pics.sum())}")

    # ----- 2. Per-region audit -----
    for r in REGIONS:
        section(f"[2.{r}] REGION {r}")
        norm_col, class_col = f"{r}_norm", f"{r}_class"
        cleaned_col, status_col = f"{r}_cleaned", f"{r}_status"
        right_col, left_col = f"{r}_right", f"{r}_left"

        # 2a. Sum of classes
        cls_counts = proc[class_col].value_counts().to_dict()
        total = sum(cls_counts.values())
        check(f"sum(class counts) == {len(proc)}", total == len(proc), f"got {total}", issues)
        out(f"      classes: {cls_counts}")

        # 2b. Sum of statuses
        st_counts = proc[status_col].value_counts().to_dict()
        total_status = sum(st_counts.values())
        check(f"sum(status counts) == {len(proc)}", total_status == len(proc),
              f"got {total_status}", issues)
        out(f"      statuses: {st_counts}")

        # 2c. N / P consistency
        n_rows = proc[proc[class_col] == "N"]
        ok_N = all(row[norm_col] == "N" for _, row in n_rows.iterrows())
        check(f"N rows have norm == 'N' ({len(n_rows)} rows)", ok_N, "", issues)

        p_rows = proc[proc[class_col] == "P"]
        ok_P = all(row[norm_col] == "P" for _, row in p_rows.iterrows())
        check(f"P rows have norm == 'P' ({len(p_rows)} rows)", ok_P, "", issues)

        # 2d. Asymmetric: regex + right/left correctness
        asym_rows = proc[proc[class_col] == "asymmetric"]
        asym_ok = True
        for _, row in asym_rows.iterrows():
            try:
                right, left, prefix = split_asymmetric(row[norm_col])
                got_r = str(row[right_col]) if pd.notna(row[right_col]) else ""
                got_l = str(row[left_col]) if pd.notna(row[left_col]) else ""
                if got_r != right or got_l != left:
                    issues.append(
                        f"{r}: wolf {row['serial number']} asymmetric MISMATCH "
                        f"raw={row[norm_col]!r} got=({got_r!r},{got_l!r}) "
                        f"expected=({right!r},{left!r})"
                    )
                    asym_ok = False
            except ValueError as e:
                issues.append(f"{r}: wolf {row['serial number']} asymmetric parse failed: {e}")
                asym_ok = False
        check(f"Asymmetric splits ({len(asym_rows)} rows)", asym_ok, "", issues)

        # 2e. Cleaned codes correctness
        full_rows = proc[proc[class_col] == "full"]
        n_full_bad = 0
        for _, row in full_rows.iterrows():
            if row[cleaned_col] != row[norm_col]:
                issues.append(
                    f"{r}: wolf {row['serial number']} 'full' but cleaned≠norm "
                    f"norm={row[norm_col]!r} cleaned={row[cleaned_col]!r}"
                )
                n_full_bad += 1
        check(f"Cleaned codes for 'full' rows ({len(full_rows)} rows)",
              n_full_bad == 0, f"{n_full_bad} mismatches" if n_full_bad else "", issues)

        partial_rows = proc[proc[class_col] == "partial"]
        n_partial_bad = 0
        for _, row in partial_rows.iterrows():
            expected, _ = clean_partial(row[norm_col])
            if row[cleaned_col] != expected:
                issues.append(
                    f"{r}: wolf {row['serial number']} 'partial' cleaned mismatch "
                    f"got {row[cleaned_col]!r} expected {expected!r}"
                )
                n_partial_bad += 1
        check(f"Cleaned codes for 'partial' rows ({len(partial_rows)} rows)",
              n_partial_bad == 0, "", issues)

        # 2f. partial_ambiguous justification
        amb_rows = proc[proc[status_col] == "partial_ambiguous"]
        full_and_partial_pool = [c for c in proc[cleaned_col].tolist() if c]
        n_amb_bad = 0
        for _, row in amb_rows.iterrows():
            cls = row[class_col]
            cleaned = row[cleaned_col]
            if cls == "partial":
                continue  # automatic by rule (had N/P inside)
            others = [c for c in full_and_partial_pool if c != cleaned]
            if not any(cleaned in o for o in others):
                issues.append(
                    f"{r}: wolf {row['serial number']} status=partial_ambiguous "
                    f"but cleaned={cleaned!r} is not substring of any other code"
                )
                n_amb_bad += 1
        check(f"partial_ambiguous justifications ({len(amb_rows)} rows)",
              n_amb_bad == 0, "", issues)

        # 2g. n_unique + entropy match summary
        codes_C = codes_for_version(proc, r, "C")
        nU_calc = codes_C.nunique()
        rs_row = region_summary(proc).set_index("region").loc[r]
        check(f"n_unique recomputed = summary ({nU_calc})",
              nU_calc == rs_row["n_unique"],
              f"summary={rs_row['n_unique']}", issues)

        H_calc = shannon_entropy_bits(codes_C.value_counts().values)
        # Tolerance allows for round-off in the summary (stored at 6 decimals)
        check(f"Shannon entropy recomputed = summary ({H_calc:.6f})",
              abs(H_calc - rs_row["shannon_entropy_bits"]) < 5e-6, "", issues)

        bound = np.log2(max(nU_calc, 1))
        check(f"H <= log2(n_unique): {H_calc:.4f} <= {bound:.4f}",
              H_calc <= bound + 1e-9, "", issues)

        # 2h. Top codes (find ties)
        codes_A = codes_for_version(proc, r, "A")
        if len(codes_A):
            counts = codes_A.value_counts()
            top_freq = int(counts.iloc[0])
            top_codes_list = counts[counts == top_freq].index.tolist()
            tie_marker = f" *** TIE x{len(top_codes_list)} ***" if len(top_codes_list) > 1 else ""
            out(f"      top code(s): {top_codes_list}, count={top_freq}{tie_marker}")

        # 2i. Rank-freq percent sum ~= 100
        for v in ("A", "B", "C"):
            rf = rank_frequency(proc, r, v)
            if len(rf):
                pct_sum = float(rf["percent"].sum())
                check(f"rank-freq percent sum ≈ 100 (version {v}): {pct_sum:.4f}",
                      abs(pct_sum - 100) < 0.01, "", issues)

        # 2j. Color/pattern coverage (relevant regions)
        if r in {"A1", "A2", "C6", "D8"}:
            color_col, pattern_col = f"{r}_color", f"{r}_pattern"
            applicable = proc[proc[class_col].isin(["full", "partial"])]
            no_split = applicable[applicable[color_col].isna()]
            check(f"all full/partial wolves have color/pattern split "
                  f"({len(applicable) - len(no_split)}/{len(applicable)})",
                  len(no_split) == 0,
                  f"{len(no_split)} missing", issues)
            if len(no_split):
                for _, row in no_split.head(5).iterrows():
                    out(f"        missing: {row['serial number']} cleaned={row[cleaned_col]!r}")

    # ----- 3. Cross-region check -----
    section("[3] CROSS-REGION CONSISTENCY")
    n_missing = 0
    for _, row in proc.iterrows():
        for r in REGIONS:
            if pd.isna(row.get(f"{r}_status")):
                issues.append(f"Wolf {row['serial number']} missing {r}_status")
                n_missing += 1
    check(f"All wolves have all 9 region statuses ({len(proc)} wolves x 9)",
          n_missing == 0, f"{n_missing} missing" if n_missing else "", issues)

    # ----- 4. Anomalous codes -----
    section("[4] LOOKING FOR ANOMALIES")

    # Codes containing characters outside expected set
    expected_chars = set("abcdefghijklmnopqrstuvwxyzNPRL0123456789")
    for r in REGIONS:
        for _, row in proc.iterrows():
            v = row[f"{r}_norm"]
            if v is None:
                continue
            unexpected = set(str(v)) - expected_chars
            if unexpected:
                msg = (f"{r}: wolf {row['serial number']} code {v!r} "
                       f"contains unexpected chars: {unexpected}")
                issues.append(msg)
                out(f"  !! {msg}")
    out(f"  Total wolves scanned for unexpected characters: {len(proc) * len(REGIONS)}")

    # Wolves whose >5 regions are N/empty (suspicious data quality)
    bad_count_threshold = 5
    suspicious = []
    for _, row in proc.iterrows():
        bad = sum(1 for r in REGIONS if row[f"{r}_status"] in ("N", "P", "empty"))
        if bad >= bad_count_threshold:
            suspicious.append((row["serial number"], bad))
    if suspicious:
        out(f"  !! Wolves with {bad_count_threshold}+ N/P/empty regions:")
        for sn, n in suspicious:
            out(f"     {sn}: {n}/9 unobservable")
    else:
        out(f"  No wolves with {bad_count_threshold}+ N/P/empty regions.")

    # ----- 5. Spot-check sample -----
    section("[5] SAMPLE — first 3 wolves, all 9 regions")
    for _, row in proc.head(3).iterrows():
        out(f"  Wolf {row['serial number']} (#pictures={row['#pictures']}, area={row.get('area','')}):")
        for r in REGIONS:
            raw = row[r] if pd.notna(row[r]) else "(empty)"
            stat = row[f"{r}_status"]
            cleaned = row[f"{r}_cleaned"] or "—"
            extras = ""
            if pd.notna(row.get(f"{r}_right")):
                extras = f"  right={row[f'{r}_right']!r} left={row[f'{r}_left']!r}"
            out(f"    {r}: raw={str(raw)!r:<15} status={stat:<20} cleaned={cleaned!r}{extras}")

    # ----- 6. Summary -----
    section("[6] AUDIT SUMMARY")
    if issues:
        out(f"  !! {len(issues)} ISSUES FOUND:")
        for i, issue in enumerate(issues, 1):
            out(f"    {i}. {issue}")
    else:
        out("  ALL CHECKS PASSED. No data inconsistencies detected.")

    # Save report to file
    report_path = OUTPUT_DIR / "audit_report.md"
    report_text = "# Wolf Pelt Analysis — Audit Report\n\n```\n" + tee.get_report() + "\n```\n"
    report_path.write_text(report_text, encoding="utf-8")
    print(f"\n📄 Report saved: {report_path}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
